x-workspace-source: &WORKSPACE_SOURCE "~/ws"
x-start-sh-source: &START_SH_SOURCE "~/dockerfiles/scripts/start.bash"
x-vscode-extensions-installer-source: &VSCODE_EXTENSIONS_INSTALLER_SOURCE "~/dockerfiles/scripts/install_vscode_extensions.sh"

services:
  ws:
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    tty: true
    privileged: true
    environment:
      DISPLAY: $DISPLAY
      TERM: screen-256color
      LANG: C.UTF-8
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: *START_SH_SOURCE
        target: /home/user/start.bash
      - type: bind
        source: *VSCODE_EXTENSIONS_INSTALLER_SOURCE
        target: /home/user/install_vscode_extensions.sh
      - type: bind
        source: *WORKSPACE_SOURCE
        target: /home/user/ws
      - type: volume
        source: zypp-cache
        target: /var/cache/zypp
    working_dir: /home/user/ws
    command: /bin/bash /home/user/start.bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  zypp-cache:
    name: opensuse-leap15.6-zypp-cache
