x-workspace-source: &WORKSPACE_SOURCE "~/ws"
x-start-sh-source: &START_SH_SOURCE "~/dockerfiles/scripts/start.bash"
x-vscode-extensions-installer-source: &VSCODE_EXTENSIONS_INSTALLER_SOURCE "~/dockerfiles/scripts/install_vscode_extensions.sh"

services:
  ws:
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    tty: true
    network_mode: host
    privileged: true
    environment:
      DISPLAY: $DISPLAY
      TERM: screen-256color
      LANG: C.UTF-8
      NVIDIA_DRIVER_CAPABILITIES: all
      XAUTHORITY: $XAUTHORITY
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
      - type: bind
        source: $XAUTHORITY
        target: $XAUTHORITY
        read_only: true
      - type: bind
        source: *START_SH_SOURCE
        target: ${MY_HOME}/start.bash
        read_only: true
      - type: bind
        source: *VSCODE_EXTENSIONS_INSTALLER_SOURCE
        target: ${MY_HOME}/install_vscode_extensions.sh
        read_only: true
      - type: bind
        source: *WORKSPACE_SOURCE
        target: ${MY_HOME}/ws
      - type: volume
        source: apt-cache-apt-lists
        target: /var/lib/apt/lists
      - type: volume
        source: apt-cache-apt-archives
        target: /var/cache/apt/archives
    working_dir: ${MY_HOME}/ws
    command: /bin/bash ${MY_HOME}/start.bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  apt-cache-apt-lists:
    name: ubuntu24.04-apt-cache-apt-lists
  apt-cache-apt-archives:
    name: ubuntu24.04-apt-cache-apt-archives
