x-workspace-source: &WORKSPACE_SOURCE "~/ws"

services:
  ws:
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    tty: true
    privileged: true
    environment:
      TERM: screen-256color
      LANG: C.UTF-8
      DISPLAY: $DISPLAY
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ~/dockerfiles/scripts/start.bash
        target: /home/user/start.bash
      - type: bind
        source: *WORKSPACE_SOURCE
        target: /home/user/ws
      - type: volume
        source: apt-cache-apt-lists
        target: /var/lib/apt/lists
      - type: volume
        source: apt-cache-apt-archives
        target: /var/cache/apt/archives
    working_dir: /home/user/ws
    command: /bin/bash /home/user/start.bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  apt-cache-apt-lists:
    name: ubuntu22.04-apt-cache-apt-lists
  apt-cache-apt-archives:
    name: ubuntu22.04-apt-cache-apt-archives
